services:
  workspace-backend:
    build: .
    image: jkazama/ddd-java
    command: /bin/sh -c "chown -R $UID:$GID /home/vscode/.gradle /home/vscode/.vscode-server; while sleep 1000; do :; done"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - ..:/home/vscode/workspace:cached
      - ~/.ssh:/home/vscode/.ssh
      - backend-gradle-cache:/home/vscode/.gradle
      - backend-extensions:/home/vscode/.vscode-server/extensions
    working_dir: /home/vscode/workspace

volumes:
  backend-gradle-cache:
  backend-extensions:
